---

os:
  timezone: "Europe/London"
  packages:
    - brotli
    - fail2ban
    - git
    - memcached
    - mcrypt
    - mysql-client
    - net-tools
    - locate
    - sysstat
    - logrotate
  admin_user: admin
